// Writes every species' stage, attribute and evolution rules (Digital Monster Color,
// as Digitama Hatchery documents them) to hooks/species.gen.ts, for the evolution.
// Usage: bun scripts/build-species.ts        (reads data/dmc.json: run scripts/crawl-humulos.ts first)
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import type { Species } from './crawl-humulos'

const ROOT = join(import.meta.dir, '..')
const STAGES: Record<string, string> = { I: 'baby1', II: 'baby2', III: 'rookie', IV: 'champion', V: 'ultimate', VI: 'mega', 'VI+': 'superMega' }
const REQUIREMENTS = ['careMistakes', 'training', 'overfeed', 'sleepDisturbances', 'battles', 'winRatio'] as const

const chart = (await Bun.file(join(ROOT, 'data/dmc.json')).json()) as {
  versions: { version: string; chart: string; ids: string[] }[]
  species: Record<string, Species>
}

let jogress = 0
const out: (readonly [string, object])[] = Object.values(chart.species).map(s => {
  const rules = s.evolvesTo.flatMap(e =>
    e.options.flatMap(o => {
      const option = o as Record<string, unknown>
      // A jogress needs a partner: `/digi jogress` brings one, the rules never do.
      if (option.jogress) {
        jogress++
        return [{ to: e.to, jogress: (option.jogress as { with: string }).with }]
      }
      return [{ to: e.to, ...Object.fromEntries(REQUIREMENTS.filter(k => option[k]).map(k => [k, option[k]])) }]
    }),
  )
  return [s.id, { name: s.name, stage: STAGES[s.stage] ?? s.stage, attribute: s.attribute, power: s.power, rules }] as const
})
// Each version's egg, hatching into the version's first Baby I (the sprites name them egg1 … egg5).
const eggs = chart.versions.map(
  v => [`egg${v.chart.slice(1)}`, { name: `${v.version} Digitama`, stage: 'egg', attribute: 'Free', power: null, rules: [{ to: v.ids[0]! }] }] as const,
)
out.unshift(...eggs)

writeFileSync(
  join(ROOT, 'plugin/hooks/species.gen.ts'),
  `// Generated by scripts/build-species.ts from data/dmc.json: do not edit.
// Digital Monster Color evolution rules, via humulos.com (Digitama Hatchery).
import type { SpeciesRules } from './growth'

export const SPECIES: Record<string, SpeciesRules> = {
${out.map(([id, s]) => `  ${JSON.stringify(id)}: ${JSON.stringify(s)},`).join('\n')}
}
`,
)
console.log(`wrote plugin/hooks/species.gen.ts (${out.length} species and eggs, ${jogress} jogress options)`)
